/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Concurrency
 */
export interface Concurrency {
    /**
     * 
     * @type {number}
     * @memberof Concurrency
     */
    step?: number;
    /**
     * 
     * @type {number}
     * @memberof Concurrency
     */
    before_count?: number;
    /**
     * 
     * @type {number}
     * @memberof Concurrency
     */
    after_count?: number;
}


