/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Account } from './account';
import { Proxy } from './proxy';
import { Reservation } from './reservation';

/**
 * 
 * @export
 * @interface Config
 */
export interface Config {
    /**
     * 
     * @type {Account}
     * @memberof Config
     */
    account: Account;
    /**
     * 
     * @type {boolean}
     * @memberof Config
     */
    dry_run?: boolean;
    /**
     * 
     * @type {Proxy}
     * @memberof Config
     */
    proxy: Proxy;
    /**
     * 
     * @type {Reservation}
     * @memberof Config
     */
    reservation: Reservation;
    /**
     * 
     * @type {number}
     * @memberof Config
     */
    port?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Config
     */
    do_not_dump?: boolean;
}


