/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Concurrency } from './concurrency';
import { CourseOption } from './course-option';
import { ReservationSlot } from './reservation-slot';
import { Retry } from './retry';
import { Timer } from './timer';

/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    prefectures?: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    area1?: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    area2?: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    directory_name?: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    cast_id?: string;
    /**
     * 
     * @type {Array<Array<ReservationSlot>>}
     * @memberof Reservation
     */
    schedule?: Array<Array<ReservationSlot>>;
    /**
     * 
     * @type {Array<CourseOption>}
     * @memberof Reservation
     */
    options?: Array<CourseOption>;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    message?: string;
    /**
     * 
     * @type {Retry}
     * @memberof Reservation
     */
    retry?: Retry;
    /**
     * 
     * @type {Timer}
     * @memberof Reservation
     */
    timer?: Timer;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    course_min?: number;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    course_max?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Reservation
     */
    slot_finder_ascending?: boolean;
    /**
     * 
     * @type {Concurrency}
     * @memberof Reservation
     */
    concurrency?: Concurrency;
}


