/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Retry
 */
export interface Retry {
    /**
     * 
     * @type {boolean}
     * @memberof Retry
     */
    unlimited?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Retry
     */
    interval?: number;
    /**
     * 
     * @type {number}
     * @memberof Retry
     */
    max_retry?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Retry
     */
    use_deadline?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Retry
     */
    deadline?: number;
}


