/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Word
 */
export interface Word {
    /**
     * 
     * @type {string}
     * @memberof Word
     */
    word: string;
    /**
     * 
     * @type {number}
     * @memberof Word
     */
    cosine_similarity: number;
}


