/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { DistanceResponse } from '../model';
// @ts-ignore
import { HTTPValidationError } from '../model';
// @ts-ignore
import { ImageResponse } from '../model';
// @ts-ignore
import { PredictResponse } from '../model';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Home
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Predict Words
         * @param {string} wordA 
         * @param {any} wordB 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        predictWordsDistanceGet: async (wordA: string, wordB: any, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'wordA' is not null or undefined
            assertParamExists('predictWordsDistanceGet', 'wordA', wordA)
            // verify required parameter 'wordB' is not null or undefined
            assertParamExists('predictWordsDistanceGet', 'wordB', wordB)
            const localVarPath = `/distance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (wordA !== undefined) {
                localVarQueryParameter['word_a'] = wordA;
            }

            if (wordB !== undefined) {
                localVarQueryParameter['word_b'] = wordB;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Predict Words
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        predictWordsWordsGet: async (q: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('predictWordsWordsGet', 'q', q)
            const localVarPath = `/words`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search Image
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchImageImagesGet: async (q: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('searchImageImagesGet', 'q', q)
            const localVarPath = `/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Home
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async homeGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.homeGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Predict Words
         * @param {string} wordA 
         * @param {any} wordB 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async predictWordsDistanceGet(wordA: string, wordB: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DistanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.predictWordsDistanceGet(wordA, wordB, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Predict Words
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async predictWordsWordsGet(q: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PredictResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.predictWordsWordsGet(q, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Search Image
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchImageImagesGet(q: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchImageImagesGet(q, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Home
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeGet(options?: any): AxiosPromise<any> {
            return localVarFp.homeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Predict Words
         * @param {string} wordA 
         * @param {any} wordB 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        predictWordsDistanceGet(wordA: string, wordB: any, options?: any): AxiosPromise<DistanceResponse> {
            return localVarFp.predictWordsDistanceGet(wordA, wordB, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Predict Words
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        predictWordsWordsGet(q: string, options?: any): AxiosPromise<PredictResponse> {
            return localVarFp.predictWordsWordsGet(q, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search Image
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchImageImagesGet(q: string, options?: any): AxiosPromise<ImageResponse> {
            return localVarFp.searchImageImagesGet(q, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Home
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public homeGet(options?: any) {
        return DefaultApiFp(this.configuration).homeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Predict Words
     * @param {string} wordA 
     * @param {any} wordB 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public predictWordsDistanceGet(wordA: string, wordB: any, options?: any) {
        return DefaultApiFp(this.configuration).predictWordsDistanceGet(wordA, wordB, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Predict Words
     * @param {string} q 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public predictWordsWordsGet(q: string, options?: any) {
        return DefaultApiFp(this.configuration).predictWordsWordsGet(q, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search Image
     * @param {string} q 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchImageImagesGet(q: string, options?: any) {
        return DefaultApiFp(this.configuration).searchImageImagesGet(q, options).then((request) => request(this.axios, this.basePath));
    }
}
